### ISSUE TITLE
在父组件中给content一个值但是不显示在界面中是怎么回事呢？

### ISSUE THREAD

**Issue by Realo7** [font-size/vue-quill-simple-demo#1]
在数据库中取出之前编辑的内容，但是不能在编辑器中显示。编辑器中显示placeholder，应该通过什么方式把数据显示在编辑器中呢？

**Comment by Realo7** [comment]
this.$refs.mychild.content，我使用这个看content是有值的，但是不在编辑器内显示，我应该更新什么内容

**Comment by font-size** [comment]
一般来说，你可以使用pasteHTML。语法是quill.clipboard.dangerouslyPasteHTML(selection, value);例如quill.clipboard.dangerouslyPasteHTML(5, '&nbsp;<b>World</b>');，在光标第5个位置插入World字符。
如果是纯文本，也可以使用quill.setText('World\n');

**Comment by font-size** [comment]
mychild指的是quill实例的话，如果直接设置this.$refs.mychild.children[0].innerHTML = value也是可以的，但不建议。

**Comment by Realo7** [comment]
问题解决了，谢谢您的帮助。使用的是quill.pasteHTML的方法，this.$refs.mychild.quill.clipboard.dangerouslyPasteHTML(0, this.content1)，这样使用的,我是把你的项目封装成子组件调用的。
